export const dataBOQ = [
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "TenCongTac",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Tên công tác",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "NhaSanXuat",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Nhà sản xuất",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "XuatSu",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Xuất sứ",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "YeuCauKyThuat",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Yêu cầu kỹ thuật",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "DonVi",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Đơn vị",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "KhoiLuong",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Khối lượng",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "GhiChu",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Ghi chú",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },

  //nhà thầu nhập
  {
    formula: "{\"formula\":\"\"}",
    key: "MaHieu",
    listBindingField: [],
    lookup: "",
    name: "Mã hiệu (NT)",
    options: [],
    position: "100",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "NhaSanXuatNT",
    listBindingField: [],
    lookup: "",
    name: "Nhà sản xuất (NT)",
    options: [],
    position: "100",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "XuatSu",
    listBindingField: [],
    lookup: "",
    name: "Xuất sứ (NT)",
    options: [],
    position: "100",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "YecCauKyThuat",
    listBindingField: [],
    lookup: "",
    name: "Yêu cầu kỹ thuật (NT)",
    options: [],
    position: "100",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "DonVi",
    listBindingField: [],
    lookup: "",
    name: "Đơn vị (NT)",
    options: [],
    position: "100",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "KhoiLuongNT",
    listBindingField: [],
    lookup: "",
    name: "Khối lượng (NT)",
    options: [],
    position: "100",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "GhiChu",
    listBindingField: [],
    lookup: "",
    name: "Ghi chú (NT)",
    options: [],
    position: "100",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },

]

export const dataBOQ_FINACE = [
  {
    formula: "{\"formula\":\"\"}",
    key: "TenCongTac",
    listBindingField: [],
    lookup: "",
    name: "Tên công tác",
    options: [],
    position: "0",
    readOnly: 1,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: true
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "NhaSanXuat",
    listBindingField: [],
    lookup: "",
    name: "Nhà sản xuất",
    options: [],
    position: "0",
    readOnly: 1,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: true
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "XuatSu",
    listBindingField: [],
    lookup: "",
    name: "Xuất sứ",
    options: [],
    position: "0",
    readOnly: 1,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: true
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "YeuCauKyThuat",
    listBindingField: [],
    lookup: "",
    name: "Yêu cầu kỹ thuật",
    options: [],
    position: "0",
    readOnly: 1,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: true
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "DonVi",
    listBindingField: [],
    lookup: "",
    name: "Đơn vị",
    options: [],
    position: "0",
    readOnly: 1,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: true
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "KhoiLuong",
    listBindingField: [],
    lookup: "",
    name: "Khối lượng",
    options: [],
    position: "0",
    readOnly: 1,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: true
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "GhiChu",
    listBindingField: [],
    lookup: "",
    name: "Ghi chú",
    options: [],
    position: "0",
    readOnly: 1,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: true
  },

  //nhà thầu nhập
  {
    formula: "{\"formula\":\"\"}",
    key: "MaHieu",
    listBindingField: [],
    lookup: "",
    name: "Mã hiệu (NT)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "NhaSanXuat",
    listBindingField: [],
    lookup: "",
    name: "Nhà sản xuất (NT)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "XuatSu",
    listBindingField: [],
    lookup: "",
    name: "Xuất sứ (NT)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "YecCauKyThuat",
    listBindingField: [],
    lookup: "",
    name: "Yêu cầu kỹ thuật (NT)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "DonVi",
    listBindingField: [],
    lookup: "",
    name: "Đơn vị (NT)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "KhoiLuong",
    listBindingField: [],
    lookup: "",
    name: "Khối lượng (NT)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "GhiChu",
    listBindingField: [],
    lookup: "",
    name: "Ghi chú (NT)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },


  {
    formula: "{\"formula\":\"\"}",
    key: "DonGiaVatTu",
    listBindingField: [],
    lookup: "",
    name: "Đơn giá vật tư (VND)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "DonGiaNhanCong",
    listBindingField: [],
    lookup: "",
    name: "Đơn giá nhân công (NT)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "TongDonGia",
    listBindingField: [],
    lookup: "",
    name: "Tổng đơn giá (VND)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },

  {
    formula: "{\"formula\":\"\"}",
    key: "ThanhTienVatTu",
    listBindingField: [],
    lookup: "",
    name: "Thành tiền vật tư (VND)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "ThanhTienNhanCong",
    listBindingField: [],
    lookup: "",
    name: "Thành tiền nhân công (VND)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "TongThanhTien",
    listBindingField: [],
    lookup: "",
    name: "Tổng thành tiền (VND)",
    options: [],
    position: "0",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },

]


export const dataTCTN = [
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "MaVatTu",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Mã vật tư",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "TenVatTu",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Tên vật tư",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "ChiTieuThiNghiem",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Chỉ tiêu thí nghiệm",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "YeuCauKyThuat",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Yêu cầu kỹ thuật",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "TieuChuanThiNghiem",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Tiêu chuẩn thí nghiệm",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "TieuChuanLayMauYeuCauKyThuat",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Tiêu chuẩn lấy mẫu, yêu cầu kỹ thuật",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "TanSuatLayMauVaCaChungChiDiKem",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Tần suất lấy mẫu và các chứng chỉ đi kèm",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },

  //nhà thầu nhập
  {
    formula: "{\"formula\":\"\"}",
    key: "DapUngKhongDapUng",
    listBindingField: [],
    lookup: "",
    name: "Đáp ứng/ Không đáp ứng",
    options: [],
    position: "100",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "checkbox",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "GhiChu",
    listBindingField: [],
    lookup: "",
    name: "Ghi chú (NT)",
    options: [],
    position: "100",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },

]

export const dataPVCV = [
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "NoiDungCongViec",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Nội dung công việc",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "TrachNhiemCDT",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Trách nhiệm chủ đầu tư",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "TrachNhiemNT",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Trách nhiệm nhà thầu",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  // {
  //   formula: "{\"formula\":\"\"}",
  //   key: "GhiChu",
  //   listBindingField: [],
  //   lookup: "",
  //   name: "Ghi chú",
  //   options: [],
  //   position: "0",
  //   readOnly: 1,
  //   required: false,
  //   timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
  //   type: "text",
  //   disabled: true
  // },
  {
    formula: "{\"formula\":\"\"}",
    key: "DapUngKhongDapUng",
    listBindingField: [],
    lookup: "",
    name: "Đáp ứng/ Không đáp ứng",
    options: [],
    position: "100",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "checkbox",
    disabled: false
  },
  {
    formula: "{\"formula\":\"\"}",
    key: "GhiChu(NT)",
    listBindingField: [],
    lookup: "",
    name: "Ghi chú (NT)",
    options: [],
    position: "100",
    readOnly: 0,
    required: false,
    timeRange: "{\"startDate\":\"\",\"endDate\":\"\"}",
    type: "text",
    disabled: false
  },
]

